server:
  build: ./nginx/
  ports:
    - "80:80"
  links:
    - web:web
db:
  image: mdillon/postgis
web:
  build: .
  command: bin/rails server -e docker -p 3000 -b 0.0.0.0
  env_file: .env
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
