require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe V1::AlarmsController, type: :controller do

  create_user_company
  login_user

  before :all do
    Apartment::Tenant.switch!(@company.subdomain)
  end

  # This should return the minimal set of attributes required to create a valid
  # Alarm. As you add validations to Alarm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {code: 200, name: 'TestName'}
  }

  let(:invalid_attributes) {
    {code: nil, name: nil}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlarmsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all alarms as @alarms" do
      alarm = Alarm.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:alarms)).to eq([alarm])
    end
  end

  describe "GET #show" do
    it "assigns the requested alarm as @alarm" do
      alarm = Alarm.create! valid_attributes
      get :show, {:id => alarm.to_param}, valid_session
      expect(assigns(:alarm)).to eq(alarm)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Alarm" do
        expect {
          post :create, {:alarm => valid_attributes}, valid_session
        }.to change(Alarm, :count).by(1)
      end

      it "assigns a newly created alarm as @alarm" do
        post :create, {:alarm => valid_attributes}, valid_session
        expect(assigns(:alarm)).to be_a(Alarm)
        expect(assigns(:alarm)).to be_persisted
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved alarm as @alarm" do
        post :create, {:alarm => invalid_attributes}, valid_session
        expect(assigns(:alarm)).to be_a_new(Alarm)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name: 'NewTestName'}
      }

      it "updates the requested alarm" do
        alarm = Alarm.create! valid_attributes
        put :update, {:id => alarm.to_param, :alarm => new_attributes}, valid_session
        alarm.reload
        expect(alarm.name).to eq(new_attributes[:name])
      end

      it "assigns the requested alarm as @alarm" do
        alarm = Alarm.create! valid_attributes
        put :update, {:id => alarm.to_param, :alarm => valid_attributes}, valid_session
        expect(assigns(:alarm)).to eq(alarm)
      end
    end

    context "with invalid params" do
      it "assigns the alarm as @alarm" do
        alarm = Alarm.create! valid_attributes
        put :update, {:id => alarm.to_param, :alarm => invalid_attributes}, valid_session
        expect(assigns(:alarm)).to eq(alarm)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested alarm" do
      alarm = Alarm.create! valid_attributes
      expect {
        delete :destroy, {:id => alarm.to_param}, valid_session
      }.to change(Alarm, :count).by(-1)
    end
  end

end
