require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe V1::GatewayRolesController, type: :controller do

  create_user_company
  login_user

  before :all do
    Apartment::Tenant.switch!(@company.subdomain)
    @role_id = FactoryGirl.create(:role).id
    @gateway_id = FactoryGirl.create(:gateway).id
  end

  # This should return the minimal set of attributes required to create a valid
  # GatewayRole. As you add validations to GatewayRole, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {role_id: @role_id, gateway_id: @gateway_id}
  }

  let(:invalid_attributes) {
    {role_id: nil, gateway_id: nil}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GatewayRolesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all gateway_roles as @gateway_roles" do
      gateway_role = GatewayRole.all
      gateway_role << GatewayRole.create!(valid_attributes)
      get :index, {}, valid_session
      expect(assigns(:gateway_roles)).to eq(gateway_role)
    end
  end

  describe "GET #show" do
    it "assigns the requested gateway_role as @gateway_role" do
      gateway_role = GatewayRole.create! valid_attributes
      get :show, {:id => gateway_role.to_param}, valid_session
      expect(assigns(:gateway_role)).to eq(gateway_role)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new GatewayRole" do
        expect {
          post :create, {:gateway_role => valid_attributes}, valid_session
        }.to change(GatewayRole, :count).by(1)
      end

      it "assigns a newly created gateway_role as @gateway_role" do
        post :create, {:gateway_role => valid_attributes}, valid_session
        expect(assigns(:gateway_role)).to be_a(GatewayRole)
        expect(assigns(:gateway_role)).to be_persisted
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved gateway_role as @gateway_role" do
        post :create, {:gateway_role => invalid_attributes}, valid_session
        expect(assigns(:gateway_role)).to be_a_new(GatewayRole)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do

      let(:new_attributes) {
        {role_id: FactoryGirl.create(:role, name: 'RoleWithAnotherName').id}
      }

      it "updates the requested gateway_role" do
        gateway_role = GatewayRole.create! valid_attributes
        put :update, {:id => gateway_role.to_param, :gateway_role => new_attributes}, valid_session
        gateway_role.reload
        expect(gateway_role.role_id).to eq(new_attributes[:role_id])
      end

      it "assigns the requested gateway_role as @gateway_role" do
        gateway_role = GatewayRole.create! valid_attributes
        put :update, {:id => gateway_role.to_param, :gateway_role => valid_attributes}, valid_session
        expect(assigns(:gateway_role)).to eq(gateway_role)
      end
    end

    context "with invalid params" do
      it "assigns the gateway_role as @gateway_role" do
        gateway_role = GatewayRole.create! valid_attributes
        put :update, {:id => gateway_role.to_param, :gateway_role => invalid_attributes}, valid_session
        expect(assigns(:gateway_role)).to eq(gateway_role)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested gateway_role" do
      gateway_role = GatewayRole.create! valid_attributes
      expect {
        delete :destroy, {:id => gateway_role.to_param}, valid_session
      }.to change(GatewayRole, :count).by(-1)
    end

  end

end
