require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe V1::LampStatsController, type: :controller do

  create_user_company
  login_user

  before :all do
    Apartment::Tenant.switch!(@company.subdomain)
    @lamp_stat = FactoryGirl.create(:lamp_stat)
    @gateway = FactoryGirl.create(:gateway)
  end

  # This should return the minimal set of attributes required to create a valid
  # LampStat. As you add validations to LampStat, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      serial_number: 1
    }
  }

  let(:invalid_attributes) {
    {
      serial_number: nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LampStatsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all lamp_stats as @lamp_stats" do
      get :index, {}, valid_session
      expect(assigns(:lamp_stats)).to eq([@lamp_stat])
    end
  end

  describe "GET #show" do
    it "assigns the requested lamp_stat as @lamp_stat" do
      get :show, {:id => @lamp_stat.to_param}, valid_session
      expect(assigns(:lamp_stat)).to eq(@lamp_stat)
    end
  end

  describe "POST #create" do

    before :each do
      auth_header = @gateway.create_new_auth_token
      request.headers['accept'] = auth_header['accept']
      request.headers['access-token'] = auth_header['access-token']
      request.headers['client'] = auth_header['client']
      request.headers['uid'] = auth_header['uid']
    end

    context "with valid params" do
      it "creates a new LampStat" do
        expect {
          post :create, {format: :json, :lamp_stat => valid_attributes}, valid_session
        }.to change(LampStat, :count).by(1)
      end

      it "assigns a newly created lamp_stat as @lamp_stat" do
        post :create, {:lamp_stat => valid_attributes}, valid_session
        expect(assigns(:lamp_stat)).to be_a(LampStat)
        expect(assigns(:lamp_stat)).to be_persisted
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved lamp_stat as @lamp_stat" do
        post :create, {:lamp_stat => invalid_attributes}, valid_session
        expect(assigns(:lamp_stat)).to be_a_new(LampStat)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested lamp_stat" do
      expect {
        delete :destroy, {:id => @lamp_stat.to_param}, valid_session
      }.to change(LampStat, :count).by(-1)
    end
  end

end
