require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe V1::NodesController, type: :controller do

  create_user_company
  login_user

  before :all do
    Apartment::Tenant.switch!(@company.subdomain)
  end

  # This should return the minimal set of attributes required to create a valid
  # Node. As you add validations to Node, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name: 'test', location: 'POINT (127.0 0.0 1)'}
  }

  let(:invalid_attributes) {
    {name: nil}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NodesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all nodes as @nodes" do
      node = Node.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:nodes)).to eq([node])
    end
  end

  describe "GET #show" do
    it "assigns the requested node as @node" do
      node = Node.create! valid_attributes
      get :show, {:id => node.to_param}, valid_session
      expect(assigns(:node)).to eq(node)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Node" do
        expect {
          post :create, {:node => valid_attributes}, valid_session
        }.to change(Node, :count).by(1)
      end

      it "assigns a newly created node as @node" do
        post :create, {:node => valid_attributes}, valid_session
        expect(assigns(:node)).to be_a(Node)
        expect(assigns(:node)).to be_persisted
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved node as @node" do
        post :create, {:node => invalid_attributes}, valid_session
        expect(assigns(:node)).to be_a_new(Node)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name: 'newName'}
      }

      it "updates the requested node" do
        node = Node.create! valid_attributes
        put :update, {:id => node.to_param, :node => new_attributes}, valid_session
        node.reload
        expect(node.name).to eq(new_attributes[:name])
      end

      it "assigns the requested node as @node" do
        node = Node.create! valid_attributes
        put :update, {:id => node.to_param, :node => valid_attributes}, valid_session
        expect(assigns(:node)).to eq(node)
      end
    end

    context "with invalid params" do
      it "assigns the node as @node" do
        node = Node.create! valid_attributes
        put :update, {:id => node.to_param, :node => invalid_attributes}, valid_session
        expect(assigns(:node)).to eq(node)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested node" do
      node = Node.create! valid_attributes
      expect {
        delete :destroy, {:id => node.to_param}, valid_session
      }.to change(Node, :count).by(-1)
    end

  end

end
