require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe V1::UserRolesController, type: :controller do

  create_user_company
  login_user

  before :all do
    Apartment::Tenant.switch!(@company.subdomain)
  end

  # This should return the minimal set of attributes required to create a valid
  # UserRole. As you add validations to UserRole, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {user_id: @user.id, role_id: @user.role.id}
  }

  let(:invalid_attributes) {
    {user_id: nil, role_id: nil}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UserRolesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all user_roles as @user_roles" do
      user_role = UserRole.all
      user_role << UserRole.create!(valid_attributes)
      get :index, {}, valid_session
      expect(assigns(:user_roles)).to eq(user_role)
    end
  end

  describe "GET #show" do
    it "assigns the requested user_role as @user_role" do
      user_role = UserRole.create! valid_attributes
      get :show, {:id => user_role.to_param}, valid_session
      expect(assigns(:user_role)).to eq(user_role)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new UserRole" do
        expect {
          post :create, {:user_role => valid_attributes}, valid_session
        }.to change(UserRole, :count).by(1)
      end

      it "assigns a newly created user_role as @user_role" do
        post :create, {:user_role => valid_attributes}, valid_session
        expect(assigns(:user_role)).to be_a(UserRole)
        expect(assigns(:user_role)).to be_persisted
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved user_role as @user_role" do
        post :create, {:user_role => invalid_attributes}, valid_session
        expect(assigns(:user_role)).to be_a_new(UserRole)
      end

    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {role_id: FactoryGirl.create(:role, name: 'RoleWithAnotherName').id}
      }

      it "updates the requested user_role" do
        user_role = UserRole.create! valid_attributes
        put :update, {:id => user_role.to_param, :user_role => new_attributes}, valid_session
        user_role.reload
        expect(user_role.role_id).to eq(new_attributes[:role_id])
      end

      it "assigns the requested user_role as @user_role" do
        user_role = UserRole.create! valid_attributes
        put :update, {:id => user_role.to_param, :user_role => valid_attributes}, valid_session
        expect(assigns(:user_role)).to eq(user_role)
      end
    end

    context "with invalid params" do
      it "assigns the user_role as @user_role" do
        user_role = UserRole.create! valid_attributes
        put :update, {:id => user_role.to_param, :user_role => invalid_attributes}, valid_session
        expect(assigns(:user_role)).to eq(user_role)
      end

    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested user_role" do
      user_role = UserRole.create! valid_attributes
      expect {
        delete :destroy, {:id => user_role.to_param}, valid_session
      }.to change(UserRole, :count).by(-1)
    end
  end

end
